config/routes.rb
Rails.application.routes.draw do
  root 'top#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  get 'tweets' => 'tweets#index', :as => :tweets
  get 'tweets/:id' => 'tweets#show', :as => :tweet
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :twitter_user, primary_key: "user_id", foreign_key: "user_id"

  def self.find_or_create_by_object(tw)
    attrs = {
      status_id:   tw.id,
      user_id:     tw.user.id,
      body:        tw.text,
      created_at:  tw.created_at,
    }
    if tweet = Tweet.where(status_id: tw.id).first
      tweet.update_attributes(attrs)
    else
      tweet = Tweet.create(attrs)
    end
    tweet
  end

end

app/models/twitter_user.rb
class TwitterUser < ApplicationRecord

  def self.update_or_create_by_object(tw_user)
    attrs = {
      user_id:     tw_user.id,
      name:        tw_user.name,
      screen_name: tw_user.screen_name,
      profile_image_url: tw_user.profile_image_url,
    }
    if tw_user = TwitterUser.where(user_id: tw_user.id).first
      tw_user.update_attributes(attrs)
    else
      tw_user = TwitterUser.create(attrs)
    end
    tw_user
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index]

  def index
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show]

  def index
    muted_user_ids = Rails.cache.fetch(:muted_user_ids, expires_in: 1.hour) do
      client = Twitter::REST::Client.new({
        consumer_key: Settings.consumer_key,
        consumer_secret: Settings.consumer_secret,
        access_token: Settings.access_token,
        access_token_secret: Settings.access_token_secret,
      })
      client.muted_ids.attrs[:ids]
    end

    params[:search_type] ||= "all"
    tweet_ar = Tweet.where("user_id not in (?)", muted_user_ids).order("created_at desc")
    if params[:search_type] == "deleted"
      tweet_ar = tweet_ar.where.not(deleted_at: nil)
    end
    if params[:search_text].present?
      tweet_ar = tweet_ar.where("body LIKE ?", "%#{params[:search_text]}%")
    end
    tweet_ar = tweet_ar.where(user_id: params[:user_id]) if params[:user_id].present?
    if params[:screen_name].present? && twitter_user = TwitterUser.where(screen_name: params[:screen_name]).first
      tweet_ar = tweet_ar.where(user_id: twitter_user.user_id)
    end
    @tweets = tweet_ar.page(params[:page]).per(20)
  end

  def show
  end

  private

    def set_tweet
      @tweet = Tweet.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def twitter_status_url(screen_name: nil, status_id: nil)
    "https://twitter.com/#{screen_name}/status/#{status_id}"
  end

  def twitter_user_url(user_id)
    "https://twitter.com/intent/user?user_id=#{user_id}"
  end

  def keshitter_media_urls(tweet)
    return "" if tweet.media_uris.nil?
    tweet.media_uris.split("\n").map do |uri|
      "#{request.protocol}#{request.host_with_port}" + Pathname.new("/").join(Settings.media_dir_name, uri).to_s
    end.join("\n")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= request.host %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
    <%= link_to "tweets", tweets_path %>
    | <%= link_to "sign out", destroy_user_session_path, {method: :delete} %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/top/index.html.erb
<div style="font-size: 100px;text-align: center;margin: 100px;">
<%= request.host %>
</div>

app/views/tweets/index.html.erb
<% model_class = Tweet %>
<p id="notice"><%= notice %></p>

<%= form_tag(tweets_path, {:method=>"get"}) do %>
  <div>
    <%= radio_button_tag :search_type, 'all', params[:search_type] == "all" %><%= label_tag "search_type_all", "all" %>
    <%= radio_button_tag :search_type, 'deleted', params[:search_type] == "deleted" %><%= label_tag "search_type_deleted", "deleted" %>
  </div>
  <div>
    text: <%= text_field_tag :search_text, params[:search_text] %>
  </div>
  <div>
    user_id: <%= text_field_tag :user_id, params[:user_id] %> screen_name: <%= text_field_tag :screen_name, params[:screen_name] %>
  </div>
  <%= submit_tag "Search", :name => nil %>
<% end %>

<br>

<%= paginate @tweets %>

<table>
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:text) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:deleted_at) %></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <% user = tweet.twitter_user %>
      <tr>
        <td><%= link_to tweet.id, tweet_path(tweet), target: "_blank" %></td>
        <td class="tweet_user_name">
          <img src="<%= raw user.profile_image_url %>" alt="<%= user.name %>" title="<%= user.name %>" /><br />
          <%= link_to user.name, tweets_path(params.permit(:search_type).merge(user_id: tweet.user_id)) %>
        </td>
        <td>
          <%= auto_link(simple_format(tweet.body), :html => { :target => '_blank' }) %>
          <% if params[:search_type] == "deleted" %>
            <div>
              <%= auto_link(simple_format(keshitter_media_urls(tweet)), :html => { :target => '_blank' }) %>
            </div>
          <% end %>
        </td>
        <td><%= link_to tweet.created_at.strftime("%Y-%m-%d %H:%M:%S"), twitter_status_url(screen_name: user.screen_name, status_id: tweet.status_id), target: "_blank" %></td>
        <td><%= tweet.deleted_at.try(:strftime, "%Y-%m-%d %H:%M:%S") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @tweets %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>
<% twitter_user = @tweet.twitter_user %>
<p>
  <strong>Status:</strong>
  <%= @tweet.status_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= twitter_user.name %>
</p>

<p>
  <strong>Screen name:</strong>
  <%= twitter_user.screen_name %>
</p>

<p>
  <strong>Profile image url:</strong>
  <%= twitter_user.profile_image_url %>
</p>

<p>
  <strong>Body:</strong>
  <%= @tweet.body %>
</p>

<p>
  <strong>Deleted at:</strong>
  <%= @tweet.deleted_at %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @tweet.created_at %>
</p>

<%= link_to 'Back', tweets_path %>